In [1]:
import pandas as pd
from pandas import json_normalize
from pathlib import Path
from sqlalchemy import create_engine, text
import os
import json

engine_DEV_Test = create_engine(
    "mssql+pyodbc://sa:Jesus&411@Dev-Test/BCDA_Data?driver=ODBC+Driver+17+for+SQL+Server"
)

In [39]:
df = pd.read_sql_query(text("select * from eob_basetable"), con = engine_DEV_Test)
df.head()

,Claim_ID,claim_group,Patient_ID,clm_type_cd,clm_type_display,eob_type,clm_type,status,billablePeriod_start,billablePeriod_end,...,admitting_dgns,insurance,subType_text,data_from,meta_lastUpdated,created,bcda_extract_date,bcda_file,extract_from,extract_to
0,carrier-33451174990,35366366483,58594950,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,cancelled,2025-03-18,2025-03-18,...,None,part-b-58594950,None,update,2026-03-13T16:52:32.207+00:00,2026-03-20T17:39:54+00:00,2026-04-06 13:43:00.113,ExplanationOfBenefit_0034_20260320174131.ndjson,2026-04-01 07:18:56.727,2026-04-05 18:08:55.827
1,carrier-33583729097,35753417356,47507798,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,cancelled,2025-04-18,2025-04-18,...,None,part-b-47507798,None,update,2026-04-04T02:52:38.983+00:00,2026-04-05T23:05:11+00:00,2026-04-06 14:04:41.830,ExplanationOfBenefit_0389_20260405230556.ndjson,2026-04-01 07:18:56.727,2026-04-05 18:08:55.827
2,carrier-33599915381,35773087785,97356385,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,cancelled,2025-04-11,2025-04-11,...,None,part-b-97356385,None,update,2026-03-27T15:48:24.646+00:00,2026-03-27T16:41:53+00:00,2026-04-01 08:30:16.287,ExplanationOfBenefit_0358_20260327164250.ndjson,2026-03-29 18:07:12.047,2026-04-01 07:18:56.727
3,carrier-33625713536,35826919127,385686953,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,cancelled,2025-04-11,2025-04-11,...,None,part-b-385686953,None,update,2026-03-27T16:01:48.639+00:00,2026-03-27T16:41:49+00:00,2026-04-01 08:29:28.490,ExplanationOfBenefit_0335_20260327164250.ndjson,2026-03-29 18:07:12.047,2026-04-01 07:18:56.727
4,carrier-33641185603,35834195122,57984040,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,cancelled,2025-04-15,2025-04-15,...,None,part-b-57984040,None,update,2026-03-27T15:45:20.493+00:00,2026-03-27T16:41:33+00:00,2026-04-01 08:26:13.927,ExplanationOfBenefit_0240_20260327164250.ndjson,2026-03-29 18:07:12.047,2026-04-01 07:18:56.727

In [7]:
df_carrier = df[(df['eob_type']== 'CARRIER') & (df['payment_amount_value']>250) & (df['status']!= 'cancelled')]
df_carrier.sort_values(by = 'payment_amount_value', ascending = False)

,Claim_ID,claim_group,Patient_ID,clm_type_cd,clm_type_display,eob_type,clm_type,status,billablePeriod_start,billablePeriod_end,...,admitting_dgns,insurance,subType_text,data_from,meta_lastUpdated,created,bcda_extract_date,bcda_file,extract_from,extract_to
36353,carrier-34900736936,39517818808,364444462,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,active,2026-02-11,2026-02-11,...,None,part-b-364444462,None,update,2026-03-13T17:05:46.917+00:00,2026-03-20T17:40:32+00:00,2026-04-06 13:51:52.967,ExplanationOfBenefit_0178_20260320174131.ndjson,2026-04-01 07:18:56.727,2026-04-05 18:08:55.827
88600,carrier-34998229400,39297397911,99501349,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,active,2026-01-28,2026-01-28,...,None,part-b-99501349,None,update,2026-04-04T02:56:25.187+00:00,2026-04-05T23:05:18+00:00,2026-04-06 14:07:22.903,ExplanationOfBenefit_0433_20260405230556.ndjson,2026-04-01 07:18:56.727,2026-04-05 18:08:55.827
124070,carrier-35097549723,40023123954,99501349,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,active,2026-03-25,2026-03-25,...,None,part-b-99501349,None,inserted,2026-04-24T16:11:25.457+00:00,2026-04-27T11:39:08+00:00,2026-04-27 06:45:51.090,ExplanationOfBenefit_0071_20260427114135.ndjson,2026-04-19 18:08:48.720,2026-04-27 06:43:46.743
133732,carrier-35115462725,40019431154,364444462,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,active,2026-04-08,2026-04-08,...,None,part-b-364444462,None,inserted,2026-04-24T16:16:45.105+00:00,2026-04-27T11:40:28+00:00,2026-04-27 06:50:14.800,ExplanationOfBenefit_0314_20260427114135.ndjson,2026-04-19 18:08:48.720,2026-04-27 06:43:46.743
124071,carrier-35097549724,40020238954,99501349,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,active,2026-03-25,2026-03-25,...,None,part-b-99501349,None,inserted,2026-04-24T16:11:25.457+00:00,2026-04-27T11:39:08+00:00,2026-04-27 06:45:51.090,ExplanationOfBenefit_0071_20260427114135.ndjson,2026-04-19 18:08:48.720,2026-04-27 06:43:46.743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127567,carrier-35102818472,39524316348,307214761,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,active,2026-02-04,2026-02-04,...,None,part-b-307214761,None,inserted,2026-04-24T16:14:31.130+00:00,2026-04-27T11:39:22+00:00,2026-04-27 06:46:43.363,ExplanationOfBenefit_0115_20260427114135.ndjson,2026-04-19 18:08:48.720,2026-04-27 06:43:46.743
54324,carrier-34940717828,39609950537,71230047,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,active,2026-03-03,2026-03-03,...,None,part-b-71230047,None,update,2026-03-20T19:01:41.389+00:00,2026-03-27T16:41:43+00:00,2026-04-01 08:28:06.680,ExplanationOfBenefit_0295_20260327164250.ndjson,2026-03-29 18:07:12.047,2026-04-01 07:18:56.727
99566,carrier-35024811968,39189001945,435874769,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,active,2026-01-13,2026-01-23,...,None,part-b-435874769,None,inserted,2026-04-10T16:01:51.694+00:00,2026-04-12T23:02:16+00:00,2026-04-12 18:14:28.327,ExplanationOfBenefit_0321_20260412230320.ndjson,2026-04-05 18:08:55.827,2026-04-12 18:06:14.810
60189,carrier-34952529991,39019886159,40654473,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,active,2026-01-03,2026-01-06,...,None,part-b-40654473,None,update,2026-03-27T15:43:31.081+00:00,2026-03-27T16:42:06+00:00,2026-04-01 08:32:43.963,ExplanationOfBenefit_0427_20260327164250.ndjson,2026-03-29 18:07:12.047,2026-04-01 07:18:56.727
130838,carrier-35107980214,40018352314,530559035,71,"Local carrier non-durable medical equipment, p...",CARRIER,professional,active,2026-03-31,2026-03-31,...,None,part-b-530559035,None,inserted,2026-04-24T16:23:33.430+00:00,2026-04-27T11:40:47+00:00,2026-04-27 06:51:17.847,ExplanationOfBenefit_0370_20260427114135.ndjson,2026-04-19 18:08:48.720,2026-04-27 06:43:46.743

In [13]:
df[df['payment_amount_value']>= 0].groupby('eob_type').agg({
    'payment_amount_value': ['mean', 'median', 'min', 'max']
})

           payment_amount_value
                           mean    median  min        max
eob_type
CARRIER              107.829951     53.09  0.0   32076.83
DME                  213.012590     76.96  0.0   19635.44
HHA                 1675.829844   1600.92  0.0    4595.57
HOSPICE             4124.767290   4686.65 -0.0   11032.20
INPATIENT          15296.076373  11785.90 -0.0  126008.52
OUTPATIENT           737.680492    111.75  0.0   71323.91
SNF                 8483.536821   8433.56 -0.0   36742.16

In [ ]:
df['billablePeriod_start'] = pd.to_datetime(df['billablePeriod_start'])
df['billablePeriod_end'] = pd.to_datetime(df['billablePeriod_end'])

df['los'] = (df['billablePeriod_end'] - df['billablePeriod_start']).dt.days

In [41]:
df.to_json('eob_data.json', orient = 'records', lines = True)

In [24]:
df

In [74]:
import os 
from pathlib import Path


dir_onedrive = next(p for p in Path(os.environ["USERPROFILE"]).iterdir()
                if p.name.startswith("OneDrive - "))

path = Path(
    dir_onedrive
)

parts=[]
for file in path.rglob('*.sql'):
    parts.append(str(file).rsplit('\\',1))

sorted(parts, key=lambda x: (x[0], x[1]))

[['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com',
  'LDFLogFileShrink.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com',
  'Test_consecutive_job.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com', 'add_jobs_Script.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\ERRORS',
  'RecoveryPending.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'ACODoctor_RiskScore.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'ACO_Beneficiaries_AvgRiskScore.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'ACO_Beneficiaries_CountByAttributionType.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'ACO_Goals_PatientNeedMDVisit.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'AEXPU_2017.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'AmountPaid_6Months_PriorToDeath.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Appointment_Facility_Doctor_Update.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Attribution_Counts.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Attribution_Drops_LastVisit.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'BCP_Test.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Benchmark_AllPatients_Detail_2017.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Benchmark_AllPatients_Summary_2017.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CCLF_FinalData_UpdateClaimDisposition_Physician.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'COPD_Initiative_10152020.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_2017.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_2018.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_2019.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_2020.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_2021.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_CCM_OfficeVisit.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_CohertManager_2017.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_CohertManager_2018.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_CohertManager_2019.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_CohertManager_2020.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_CohertManager_2021.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_ED.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_HCPCS.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_HospitalSpecialty.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_LOS.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_Medication_2018.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_Medication_2019.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_Medication_2020.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_AllAttributed_TimeLine.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_CCM_OfficeVisit.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ClaimPlaceOfService_All.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_CohertManager.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_CohertManager_2017.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_CohertManager_2018.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_CohertManager_2019.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_CohertManager_2020.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_CohertManager_2021.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_DischargeFromTo.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_DischargeTo_HHA.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_DrugsRequiringSpecificId_DoesNotWorkCorrectly.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ED.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_EDToHospitalAdmit.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_EpisodeFrom.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_EpisodeFrom_UpdateDRG.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ExpenseType.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ExpenseType1.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ExpenseType1_SNF.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ExpenseType2.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ExpenseType3.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ExpenseType3_Doctor.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ExpenseType3_PCP.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_HCCRiskScore.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_HCCRiskScore_Try2.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_HCPCS.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_HHA_SNF.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_HomeHealthPatients.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_HomeHealthTotalCost.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_HospitalInpatient.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_HospitalSpecialty.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_HospitalSpecialty_Procedures.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_HospitalSpecialty_Provider.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_LOS.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_LOS_UpdateDRG.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Medication_2017.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Medication_2018.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Medication_2019.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Medication_2020.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Medication_2021.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Merge_CC_With_PCM_2020.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Months.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_PhysicianClaim.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_PhysicianClaim_TaxId.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Procedure.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_QuarterOnQuarter.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_RTS2.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Readmit.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Readmit_Hospital.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Readmit_Hospital_IP_OP.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_Readmit_Hospital_VerifyData.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_SNFDetail.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_SpecialtyProvider.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_StatusOne.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_TimeLine.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_TimeLine_Pivot.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ToED.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ToED_ALLEDVisits.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_ToHospital.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilization_UpdateEpisodeFrom.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilizaton_DeleteNotFinalActionRecords.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'CostUtilizaton_HospitalUtilization.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Covid19_CollectData.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Covid19_CreateTable.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Covid19_Results.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'DGNS_I10_E78_Z79.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'DGNS_XTAB_Try3.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Detail_ByProcedureCode.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Detail_ByProcedureDiagnosisCode.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Diagnosis_BENE.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Diagnosis_ForHomeHealth.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'Diagnosis_InOneField.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'ExpenseType.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'ExpenseType_WhereClause.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'HCC_DiagnosisData_ByBENE_ByYear.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'HCC_DiagnosisData_Update.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'HealthTracking_Mipps.sql'],
 ['C:\\Users\\Levi_\\OneDrive - primecaremanagers.com\\Documentation\\Valerie Chrome Profile\\Valerie Data From local\\Python\\Reports',
  'HospitalReadmit.sql'],

In [47]:
import requests 

data = requests.post(r'https://api.restful-api.dev/objects', json={"name": "Levi", "data": "This is an object"}  ).json()
object_id = data.get('id')
df = requests.get(r'https://api.restful-api.dev/objects/' + object_id).json()
df

{'id': 'ff8081819d82fab6019de4e4e5eb7377',
 'name': 'Levi',
 'data': 'This is an object'}

In [ ]:
import os 
from pathlib import Path